// Card lists + TCGplayer market prices per set, generated by scripts/fetch-data.mjs (never edit data/ by hand).
import sv08 from '../data/cards-sv08.json' with { type: 'json' };
import sv10 from '../data/cards-sv10.json' with { type: 'json' };
import sv085 from '../data/cards-sv08.5.json' with { type: 'json' };
import sv035 from '../data/cards-sv03.5.json' with { type: 'json' };
import sv09 from '../data/cards-sv09.json' with { type: 'json' };
import me01 from '../data/cards-me01.json' with { type: 'json' };
import me02 from '../data/cards-me02.json' with { type: 'json' };
import me03 from '../data/cards-me03.json' with { type: 'json' };
import me04 from '../data/cards-me04.json' with { type: 'json' };
import me05 from '../data/cards-me05.json' with { type: 'json' };
// Simplified-Chinese card names, generated by scripts/fetch-names.mjs (set id → card number → name); a card without one keeps its English name.
import NAMES from '../data/names-zh.json' with { type: 'json' };
// Sealed booster pack prices (PriceCharting ungraded), generated by scripts/fetch-packs.mjs from each set's priceSource below.
import PACKS from '../data/packs.json' with { type: 'json' };

// p = TCGplayer market price per printing: n normal, r reverse holo, h holo, pb / mb Poké Ball / Master Ball pattern.
// name = what the player reads (the Chinese name, or the English one where names-zh.json has none); en = TCGdex's English name, for the card art and the rules that match a card by it.
export interface CardData { n: string; name: string; en: string; r: string; p: { n?: number; r?: number; h?: number; pb?: number; mb?: number } }
export interface SetData { id: string; name: string; total: number; official: number; pricesUpdated: string | null; cards: CardData[] }
export const packsUpdated = PACKS.date;
const named = (d: { id: string; name: string; total: number; official: number; pricesUpdated: string | null; cards: { n: string; name: string; r: string; p: CardData['p'] }[] }): SetData => {
  const zh = (NAMES as Record<string, Record<string, string>>)[d.id] || {};
  return { ...d, cards: d.cards.map(c => ({ ...c, en: c.name, name: zh[c.n] ?? c.name })) };
};
export const DATA: Record<string, SetData> = { sv08: named(sv08), sv10: named(sv10), 'sv08.5': named(sv085), 'sv03.5': named(sv035), sv09: named(sv09), me01: named(me01), me02: named(me02), me03: named(me03), me04: named(me04), me05: named(me05) };

// The booster pack's look, for the 3D pack (table3d.js paints it) and the packs on the shelf wall (shelf.ts). Colours read off each set's real booster art; chase = the card whose illustration fronts the pack.
export const LOOK: Record<string, { chase: string; c: [string, string, string] }> = {
  sv08: { chase: '238', c: ['#FFE15A', '#F39A1E', '#1E2C57'] },
  sv10: { chase: '231', c: ['#E4493C', '#6E1624', '#121019'] },
  'sv08.5': { chase: '161', c: ['#F6C2DB', '#7CC6DB', '#232845'] },
  'sv03.5': { chase: '199', c: ['#FF8B3D', '#C42B1C', '#1B1A20'] },
  sv09: { chase: '184', c: ['#F4B8C8', '#4D9C7D', '#1F2B33'] },
  me01: { chase: '178', c: ['#EFEBE5', '#8F6A85', '#2C2A33'] },
  me02: { chase: '125', c: ['#4FA2BB', '#2E648A', '#0E0C19'] },
  me03: { chase: '120', c: ['#F06BC8', '#2F9E6A', '#1A1328'] }, // me03–me05: colours from the chase card's art (Mega Zygarde / Greninja / Darkrai ex SIR)
  me04: { chase: '116', c: ['#7FD3F0', '#1F6FB5', '#0E1A33'] },
  me05: { chase: '116', c: ['#D9E07A', '#4A4F57', '#0B0B0E'] },
};

export interface SetConf {
  id: string; name: string; en: string; released: string; packPrice: number;
  rates: Record<string, number>; ci: Record<string, number>; sample: number; rateSource: string; priceSource: string;
}

// Hand-curated per-set config. Rates are TCGplayer's measured per-pack percentages (not the rounded "1 in N").
// ci = the article's 95% confidence half-width, used by test/sim.test.mjs. packPrice: data/packs.json (PriceCharting ungraded, dated there).
// Slot model from the same articles: rare slot = R | RR | UR; reverse #1 = reverse | ACE (| Poké Ball in PE);
// reverse #2 = reverse | IR | SIR | HR (| Master Ball in PE); plus 4 C, 3 U and a basic Energy.
export const SETS: SetConf[] = [
  {
    id: 'sv08', name: '超电突围', en: 'Surging Sparks', released: '2024-11-08',
    packPrice: PACKS.sv08,
    rates: { RR: 16.94, UR: 6.74, ACE: 5.03, IR: 7.67, SIR: 1.15, HR: 0.53 },
    ci: { RR: 0.79, UR: 0.53, ACE: 0.46, IR: 0.56, SIR: 0.22, HR: 0.15 },
    sample: 8000,
    rateSource: 'https://www.tcgplayer.com/content/article/Pok%C3%A9mon-TCG-Surging-Sparks-Pull-Rates/6ccfb6ab-f26a-4ce8-bab5-5f91c85ec70e/',
    priceSource: 'https://www.pricecharting.com/game/pokemon-surging-sparks/booster-pack',
  },
  {
    id: 'sv10', name: '命运对决', en: 'Destined Rivals', released: '2025-05-30',
    packPrice: PACKS.sv10,
    rates: { RR: 19.83, UR: 6.39, IR: 8.29, SIR: 1.06, HR: 0.67 },
    ci: { RR: 0.84, UR: 0.52, IR: 0.58, SIR: 0.22, HR: 0.17 },
    sample: 8000,
    rateSource: 'https://www.tcgplayer.com/content/article/Pok%C3%A9mon-TCG-Destined-Rivals-Pull-Rates/43ba832e-44c9-45a4-ae2e-594df2defdda/',
    priceSource: 'https://www.pricecharting.com/game/pokemon-destined-rivals/booster-pack',
  },
  {
    id: 'sv08.5', name: '棱镜进化', en: 'Prismatic Evolutions', released: '2025-01-17',
    packPrice: PACKS['sv08.5'],
    // PB / MB = Poké Ball / Master Ball pattern reverse holos. SIR 2.22 is SIRs per pack (demigod packs exist, not modelled).
    rates: { PB: 33.10, RR: 16.51, UR: 7.46, ACE: 4.68, MB: 4.92, SIR: 2.22, HR: 0.56 },
    ci: { PB: 2.60, RR: 2.05, UR: 1.45, ACE: 1.17, MB: 1.19, SIR: 0.81, HR: 0.41 },
    sample: 1200,
    rateSource: 'https://www.tcgplayer.com/content/article/Pok%C3%A9mon-TCG-Prismatic-Evolutions-Pull-Rates/d94889ea-f76a-4a13-b74d-5b0b071220a7/',
    priceSource: 'https://www.pricecharting.com/game/pokemon-prismatic-evolutions/booster-pack',
  },
  {
    id: 'sv03.5', name: '宝可梦 151', en: '151', released: '2023-09-22',
    packPrice: PACKS['sv03.5'],
    rates: { RR: 13.28, UR: 6.44, IR: 8.50, SIR: 3.11, HR: 1.94, FE: 24.83 }, // FE = cosmos-foil basic Energy
    ci: { RR: 1.57, UR: 1.13, IR: 1.29, SIR: 0.80, HR: 0.64, FE: 2.00 },
    sample: 1500,
    rateSource: 'https://www.tcgplayer.com/content/article/Pok%C3%A9mon-TCG-Scarlet-Violet%E2%80%94151-Pull-Rates/b237df74-fbb0-40d0-9e13-d69ee6e804d9/',
    priceSource: 'https://www.pricecharting.com/game/pokemon-scarlet-&-violet-151/booster-pack',
  },
  {
    id: 'sv09', name: '同行之旅', en: 'Journey Together', released: '2025-03-28',
    packPrice: PACKS.sv09,
    rates: { RR: 20.29, UR: 6.54, IR: 8.50, SIR: 1.16, HR: 0.73 },
    ci: { RR: 0.85, UR: 0.52, IR: 0.59, SIR: 0.23, HR: 0.18 },
    sample: 8000,
    rateSource: 'https://www.tcgplayer.com/content/article/Pok%C3%A9mon-TCG-Journey-Together-Pull-Rates/1b9f379f-97cb-45cc-b6f6-a1a070a422cd/',
    priceSource: 'https://www.pricecharting.com/game/pokemon-journey-together/booster-pack',
  },
  // Mega Evolution series: same pack layout (PokéBeach: packs keep the basic Energy), no ACE SPEC, and Hyper Rare is replaced by
  // Mega Hyper Rare (MHR). The articles place RR/UR in the rare slot and IR/SIR in reverse #2 but do not name MHR's slot; we put it
  // in reverse #2 where the HR it replaced sits (only co-occurrence depends on this, the per-pack rate is the measured one).
  {
    id: 'me01', name: '超级进化', en: 'Mega Evolution', released: '2025-09-26',
    packPrice: PACKS.me01,
    rates: { RR: 20.91, UR: 8.23, IR: 10.89, SIR: 0.99, MHR: 0.08 },
    ci: { RR: 1.12, UR: 0.76, IR: 0.86, SIR: 0.27, MHR: 0.08 },
    sample: 5000,
    rateSource: 'https://www.tcgplayer.com/content/article/Pok%C3%A9mon-TCG-Mega-Evolution-Pull-Rates/40cbeedc-21ce-473b-aef1-74e3969d9f91/',
    priceSource: 'https://www.pricecharting.com/game/pokemon-mega-evolution/booster-pack',
  },
  {
    id: 'me02', name: '幻影烈焰', en: 'Phantasmal Flames', released: '2025-11-14',
    packPrice: PACKS.me02,
    rates: { RR: 20.77, UR: 8.06, IR: 10.97, SIR: 1.25, MHR: 0.08 },
    ci: { RR: 1.12, UR: 0.75, IR: 0.86, SIR: 0.31, MHR: 0.08 },
    sample: 5000,
    rateSource: 'https://www.tcgplayer.com/content/article/Pok%C3%A9mon-TCG-Phantasmal-Flames-Pull-Rates/9abae60d-b7fb-448f-874e-176f78d6a6ca/',
    priceSource: 'https://www.pricecharting.com/game/pokemon-phantasmal-flames/booster-pack',
  },
  // me03–me05: the articles say the rates match the earlier Mega Evolution sets, and the per-rarity card counts match TCGdex
  // (RR 9/10/10, UR 18, IR 11, SIR 6, MHR 1). Same slots as me01/me02. me03's sample is smaller, hence its wider ci.
  {
    id: 'me03', name: '完美秩序', en: 'Perfect Order', released: '2026-03-27',
    packPrice: PACKS.me03,
    rates: { RR: 20.97, UR: 8.54, IR: 11.20, SIR: 1.23, MHR: 0.06 },
    ci: { RR: 1.34, UR: 0.92, IR: 1.03, SIR: 0.36, MHR: 0.08 },
    sample: 3500,
    rateSource: 'https://www.tcgplayer.com/content/article/Pok%C3%A9mon-TCG-Perfect-Order-Pull-Rates/73148119-ebcb-40b7-84b6-52b3a6d0c631/',
    priceSource: 'https://www.pricecharting.com/game/pokemon-perfect-order/booster-pack',
  },
  {
    id: 'me04', name: '混沌崛起', en: 'Chaos Rising', released: '2026-05-22',
    packPrice: PACKS.me04,
    rates: { RR: 20.30, UR: 8.29, IR: 10.66, SIR: 1.21, MHR: 0.10 },
    ci: { RR: 0.85, UR: 0.58, IR: 0.65, SIR: 0.23, MHR: 0.07 },
    sample: 8500,
    rateSource: 'https://www.tcgplayer.com/content/article/Pok%C3%A9mon-TCG-Chaos-Rising-Pull-Rates/304e8bfc-175a-4d31-93fe-5bb1be11e5d2/',
    priceSource: 'https://www.pricecharting.com/game/pokemon-chaos-rising/booster-pack',
  },
  {
    id: 'me05', name: '暗黑深渊', en: 'Pitch Black', released: '2026-07-17',
    packPrice: PACKS.me05,
    rates: { RR: 21.02, UR: 8.30, IR: 11.01, SIR: 1.25, MHR: 0.09 },
    ci: { RR: 1.21, UR: 0.82, IR: 0.93, SIR: 0.33, MHR: 0.09 },
    sample: 4000,
    rateSource: 'https://www.tcgplayer.com/content/article/Pok%C3%A9mon-TCG-Pitch-Black-Pull-Rates/069a5fda-2d1f-44a1-97de-b6dcdc5abfb8/',
    priceSource: 'https://www.pricecharting.com/game/pokemon-pitch-black/booster-pack',
  },
];
