// Card lists + TCGplayer market prices per set, generated by scripts/fetch-data.mjs (never edit data/ by hand).
import sv08 from '../data/cards-sv08.json' with { type: 'json' };
import sv10 from '../data/cards-sv10.json' with { type: 'json' };
import sv085 from '../data/cards-sv08.5.json' with { type: 'json' };
import sv035 from '../data/cards-sv03.5.json' with { type: 'json' };
import sv09 from '../data/cards-sv09.json' with { type: 'json' };
import me01 from '../data/cards-me01.json' with { type: 'json' };
import me02 from '../data/cards-me02.json' with { type: 'json' };
// Sealed booster pack prices (PriceCharting ungraded), generated by scripts/fetch-packs.mjs from each set's priceSource below.
import PACKS from '../data/packs.json' with { type: 'json' };

// p = TCGplayer market price per printing: n normal, r reverse holo, h holo, pb / mb Poké Ball / Master Ball pattern.
export interface CardData { n: string; name: string; r: string; p: { n?: number; r?: number; h?: number; pb?: number; mb?: number } }
export interface SetData { id: string; name: string; total: number; official: number; pricesUpdated: string | null; cards: CardData[] }
export const packsUpdated = PACKS.date;
export const DATA: Record<string, SetData> = { sv08, sv10, 'sv08.5': sv085, 'sv03.5': sv035, sv09, me01, me02 };

export interface SetConf {
  id: string; name: string; en: string; released: string; packPrice: number;
  rates: Record<string, number>; ci: Record<string, number>; sample: number; rateSource: string; priceSource: string;
}

// Hand-curated per-set config. Rates are TCGplayer's measured per-pack percentages (not the rounded "1 in N").
// ci = the article's 95% confidence half-width, used by test/sim.test.mjs. packPrice: data/packs.json (PriceCharting ungraded, dated there).
// Slot model from the same articles: rare slot = R | RR | UR; reverse #1 = reverse | ACE (| Poké Ball in PE);
// reverse #2 = reverse | IR | SIR | HR (| Master Ball in PE); plus 4 C, 3 U and a basic Energy.
export const SETS: SetConf[] = [
  {
    id: 'sv08', name: '超电突围', en: 'Surging Sparks', released: '2024-11-08',
    packPrice: PACKS.sv08,
    rates: { RR: 16.94, UR: 6.74, ACE: 5.03, IR: 7.67, SIR: 1.15, HR: 0.53 },
    ci: { RR: 0.79, UR: 0.53, ACE: 0.46, IR: 0.56, SIR: 0.22, HR: 0.15 },
    sample: 8000,
    rateSource: 'https://www.tcgplayer.com/content/article/Pok%C3%A9mon-TCG-Surging-Sparks-Pull-Rates/6ccfb6ab-f26a-4ce8-bab5-5f91c85ec70e/',
    priceSource: 'https://www.pricecharting.com/game/pokemon-surging-sparks/booster-pack',
  },
  {
    id: 'sv10', name: '命运对决', en: 'Destined Rivals', released: '2025-05-30',
    packPrice: PACKS.sv10,
    rates: { RR: 19.83, UR: 6.39, IR: 8.29, SIR: 1.06, HR: 0.67 },
    ci: { RR: 0.84, UR: 0.52, IR: 0.58, SIR: 0.22, HR: 0.17 },
    sample: 8000,
    rateSource: 'https://www.tcgplayer.com/content/article/Pok%C3%A9mon-TCG-Destined-Rivals-Pull-Rates/43ba832e-44c9-45a4-ae2e-594df2defdda/',
    priceSource: 'https://www.pricecharting.com/game/pokemon-destined-rivals/booster-pack',
  },
  {
    id: 'sv08.5', name: '棱镜进化', en: 'Prismatic Evolutions', released: '2025-01-17',
    packPrice: PACKS['sv08.5'],
    // PB / MB = Poké Ball / Master Ball pattern reverse holos. SIR 2.22 is SIRs per pack (demigod packs exist, not modelled).
    rates: { PB: 33.10, RR: 16.51, UR: 7.46, ACE: 4.68, MB: 4.92, SIR: 2.22, HR: 0.56 },
    ci: { PB: 2.60, RR: 2.05, UR: 1.45, ACE: 1.17, MB: 1.19, SIR: 0.81, HR: 0.41 },
    sample: 1200,
    rateSource: 'https://www.tcgplayer.com/content/article/Pok%C3%A9mon-TCG-Prismatic-Evolutions-Pull-Rates/d94889ea-f76a-4a13-b74d-5b0b071220a7/',
    priceSource: 'https://www.pricecharting.com/game/pokemon-prismatic-evolutions/booster-pack',
  },
  {
    id: 'sv03.5', name: '宝可梦 151', en: '151', released: '2023-09-22',
    packPrice: PACKS['sv03.5'],
    rates: { RR: 13.28, UR: 6.44, IR: 8.50, SIR: 3.11, HR: 1.94, FE: 24.83 }, // FE = cosmos-foil basic Energy
    ci: { RR: 1.57, UR: 1.13, IR: 1.29, SIR: 0.80, HR: 0.64, FE: 2.00 },
    sample: 1500,
    rateSource: 'https://www.tcgplayer.com/content/article/Pok%C3%A9mon-TCG-Scarlet-Violet%E2%80%94151-Pull-Rates/b237df74-fbb0-40d0-9e13-d69ee6e804d9/',
    priceSource: 'https://www.pricecharting.com/game/pokemon-scarlet-&-violet-151/booster-pack',
  },
  {
    id: 'sv09', name: '同行之旅', en: 'Journey Together', released: '2025-03-28',
    packPrice: PACKS.sv09,
    rates: { RR: 20.29, UR: 6.54, IR: 8.50, SIR: 1.16, HR: 0.73 },
    ci: { RR: 0.85, UR: 0.52, IR: 0.59, SIR: 0.23, HR: 0.18 },
    sample: 8000,
    rateSource: 'https://www.tcgplayer.com/content/article/Pok%C3%A9mon-TCG-Journey-Together-Pull-Rates/1b9f379f-97cb-45cc-b6f6-a1a070a422cd/',
    priceSource: 'https://www.pricecharting.com/game/pokemon-journey-together/booster-pack',
  },
  // Mega Evolution series: same pack layout (PokéBeach: packs keep the basic Energy), no ACE SPEC, and Hyper Rare is replaced by
  // Mega Hyper Rare (MHR). The articles place RR/UR in the rare slot and IR/SIR in reverse #2 but do not name MHR's slot; we put it
  // in reverse #2 where the HR it replaced sits (only co-occurrence depends on this, the per-pack rate is the measured one).
  {
    id: 'me01', name: '超级进化', en: 'Mega Evolution', released: '2025-09-26',
    packPrice: PACKS.me01,
    rates: { RR: 20.91, UR: 8.23, IR: 10.89, SIR: 0.99, MHR: 0.08 },
    ci: { RR: 1.12, UR: 0.76, IR: 0.86, SIR: 0.27, MHR: 0.08 },
    sample: 5000,
    rateSource: 'https://www.tcgplayer.com/content/article/Pok%C3%A9mon-TCG-Mega-Evolution-Pull-Rates/40cbeedc-21ce-473b-aef1-74e3969d9f91/',
    priceSource: 'https://www.pricecharting.com/game/pokemon-mega-evolution/booster-pack',
  },
  {
    id: 'me02', name: '幻影烈焰', en: 'Phantasmal Flames', released: '2025-11-14',
    packPrice: PACKS.me02,
    rates: { RR: 20.77, UR: 8.06, IR: 10.97, SIR: 1.25, MHR: 0.08 },
    ci: { RR: 1.12, UR: 0.75, IR: 0.86, SIR: 0.31, MHR: 0.08 },
    sample: 5000,
    rateSource: 'https://www.tcgplayer.com/content/article/Pok%C3%A9mon-TCG-Phantasmal-Flames-Pull-Rates/9abae60d-b7fb-448f-874e-176f78d6a6ca/',
    priceSource: 'https://www.pricecharting.com/game/pokemon-phantasmal-flames/booster-pack',
  },
];
